"""Informações do dia 19-11-2025

Revision ID: f04da2dc26a5
Revises: 5901fc0d0f15
Create Date: 2025-11-19 15:00:45.336005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04da2dc26a5'
down_revision: Union[str, Sequence[str], None] = '5901fc0d0f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
